### ISSUE TITLE
How to apply the current version LG to ComfyUI?

### ISSUE THREAD

**Issue by liusida** [daniel-lewis-ab/litegraph.js#22]
I've tried to replace this file: https://github.com/comfyanonymous/ComfyUI/blob/master/web/lib/litegraph.core.js
with this file: https://github.com/daniel-lewis-ab/litegraph.js/blob/master/build/litegraph.core.js

Though the filename is the same, but it doesn't work.

What is the procedure to apply the current version LG to ComfyUI?

**Comment by liusida** [comment]
Let's set aside any configuration or control panel for now.

I think the key part is to be compatible with current ComfyUI, so we can manually replace files or folders to enactivate the new version.

Once we can do it manually, we can think of a way to automate the process.

**Comment by liusida** [comment]
It was my attempt. But it doesn't work. I'll start from here. Make the current LG work at least partially with ComfyUI.

**Comment by liusida** [comment]
Currently, that bundle only works with this HTML file:
https://github.com/liusida/litegraph.js/blob/daniel-master/examples/use-bundle.html

**Comment by liusida** [comment]
To understand how ComfyUI uses LG, I've compared three files:

1. https://github.com/comfyanonymous/ComfyUI/blob/master/web/lib/litegraph.core.js

2. https://github.com/comfyanonymous/litegraph.js/blob/master/src/litegraph.js

3. https://github.com/jagenjo/litegraph.js/blob/master/src/litegraph.js

1. is the current LG working with ComfyUI by default, and it is the newest version (the latest commit was 2 months ago).
2. is Comfy's attempt to fix some of the bugs, and the fix will be pulled into ComfyUI's repo, but the modifications in ComfyUI's repo aren't pulled back to this repo.
3. is the original LG, which Comfy copied the original code from.

Though the filenames are different, `litegraph.js` and `litegraph.core.js` have the same content.

So, if I copied back ComfyUI's `litegraph.core.js` into the original LG and replace the `src/litegraph.js`, the original LG works perfectly.

**Comment by liusida** [comment]
Now, if I copied all the Javascript files in `forwardcompatible` branch into ComfyUI's `web/lib/` folder, the target folder will look like this:
```
-a---            6/6/2024  8:50 PM          11978 callbackhandler.js
-a---            6/6/2024  8:50 PM          31161 contextmenu.js
-a---            6/6/2024  8:50 PM           8424 dragandscale.js
-a---            6/6/2024  8:50 PM          60270 lgraph.js
-a---            6/6/2024  8:50 PM         343436 lgraphcanvas.js
-a---            6/6/2024  8:50 PM           4625 lgraphgroup.js
-a---            6/6/2024  8:50 PM          96569 lgraphnode.js
-a---           6/13/2024 11:37 AM           1507 litegraph.core.js
-a---           6/13/2024 10:03 AM         505948 litegraph.core.js.original
-a---           5/11/2024  8:15 AM          13780 litegraph.css
-a---           5/11/2024  8:15 AM            545 litegraph.extensions.js
-a---           6/13/2024 11:23 AM          46053 litegraph.js
-a---            6/6/2024  8:49 PM           2050 llink.js
```

and I modified the `litegraph.core.js` into a hack like this:
```
// litegraph.core.js


const script = document.createElement('script');
script.type = 'module';
script.textContent = `
    import { LiteGraph } from './lib/litegraph.js';
    import { LGraph } from './lib/lgraph.js';
    import { LLink } from './lib/llink.js';
    import { LGraphNode } from './lib/lgraphnode.js';
    import { LGraphGroup } from './lib/lgraphgroup.js';
    import { DragAndScale } from './lib/dragandscale.js';
    import { LGraphCanvas } from './lib/lgraphcanvas.js';
    import { ContextMenu } from './lib/contextmenu.js';

    // Attach components to the global window object for global access
    window.LiteGraph = LiteGraph;
    window.LGraph = LGraph;
    window.LLink = LLink;
    window.LGraphNode = LGraphNode;
    window.LGraphGroup = LGraphGroup;
    window.DragAndScale = DragAndScale;
    window.LGraphCanvas = LGraphCanvas;
    window.ContextMenu = ContextMenu;

    // Function to load extensions script
    function loadExtensions() {
        return import('./lib/litegraph.extensions.js');
    }

    // Load extensions script after attaching components to window object
    loadExtensions().then(() => {
        console.log('Extensions loaded successfully');
    }).catch(err => {
        console.error('Failed to load extensions:', err);
    });
    
    // Export as ES6 module
    export { LiteGraph, LGraph, LLink, LGraphNode, LGraphGroup, DragAndScale, LGraphCanvas, ContextMenu };

`;
document.head.appendChild(script);

```

Without any modification in HTML file, ComfyUI will start use the `forwardcompatible` branch. 

![image](https://github.com/daniel-lewis-ab/litegraph.js/assets/14249458/61abd463-ced4-4bfb-8ae0-c8509289c465)

**Comment by liusida** [comment]
However, our `fowardcompatible` branch is not quite compatible with ComfyUI. For example, you can see the editing area is smaller than expected, and if I click my mouse, it'll cause errors like:
```
Uncaught TypeError: LiteGraph.ContextMenu.closeAll is not a function
    at LGraphCanvas.processMouseDown (lgraphcanvas.js:699:31)
    at LGraphCanvas.processMouseDown (simpleTouchSupport.js:93:26)
    at LGraphCanvas.processMouseDown (undoRedo.js:166:29)
    at LGraphCanvas.processMouseDown (app.js:992:37)
```
closeAll is not implemented in our code.

So, if we want to keep our branch compatible with ComfyUI, we might need to start with ComfyUI's `litegraph.core.js` as our code base. Any thoughts?

**Comment by liusida** [comment]
But there's compatibility issue. For example, here in ComfyUI's `web/extensions/core/contextMenuFilter.js`, there's a redefine of contextMenu:

https://github.com/comfyanonymous/ComfyUI/blob/605e64f6d3da44235498bf9103d7aab1c95ef211/web/extensions/core/contextMenuFilter.js#L10

And it causes the bug when clicking the mouse button, the `contextMenu.closeAll()` function is not found.

I'm not sure why the original ComfyUI code works with such a refefination....

**Comment by liusida** [comment]
There are maybe two ways to make it possible for people to use our improved LG when using ComfyUI:

1. make an upgraded UI for ComfyUI, replacing its `web` directory completely.
2. make a file that can replace `litegraph.core.js`.

So maybe you are aiming for the first one, right?

**Comment by liusida** [comment]
Yeah. For solution one, I've heard about someone is using pure react-based javascript to rewrite the UI. https://github.com/canisminor1990/kitchen-comfyui (but I am not sure about React, since it is much slower)

However, solution one provides more flexibility, and I heard that Comfy himself is willing to see more UIs working with his backend Python via HTTP API. But one of the problems I can think of is to rewrite the current extensions. (or we can just copy them and follow the GPL-3.... ) (maybe it can be think as solution 3?)

If we go with solution two, I think we should take all the existing Javascript files into account, and basically make LG in that environment, so later if new LG works well, Comfy might suddenly decide to pull our code.

**Comment by daniel-lewis-ab** [comment]
I put forward a non-breaking reversion for them to pull.

Its es5, and doesn't break anything yet afaik.  I am thinking to push
changes as we figure out how to make them non-breaking and resolve issues.

**Comment by daniel-lewis-ab** [comment]
Thats encouraging.  I think ill copy you and do the same for the ES6
migration when that's the step.

Might try Proxy class for ContextMenu for now?

**Comment by liusida** [comment]
> I think we have a problem with **forward** having everything converted to classes. ComfyUI core extensions, and who know how many custom extensions, replace ContextMenu as a function, but that doesn't work with it being a class. That will happen for all the other classes too. Option a: rename all actual classes and restore original name as a function Option b: revert to simple functions I can't see any other, we can't just brake 1/2 extensions been made for ComfyUI

we don't need to consider all custom nodes (extensions), I have a list of top-100 😆   https://github.com/liusida/top-100-comfyui/

**Comment by liusida** [comment]
> Option a: rename all actual classes and restore original name as a function

I think this might be a good idea so people can migrate gradually and willingly. So if people want their users to use their custom nodes with new features in LGv1, they can tell their users to download LGv1 as a requirement.

**Comment by daniel-lewis-ab** [comment]
I mean, right now it's completely non-breaking for reversion branch, so so far it's not required.  There'll come a time when we start caring, but it's not yet.

Most of what we've been up to is stuff I'm seeing as v2 stuff.  Adding coolness to move the world forward.  v1 is going to be just straight code upgrades and boring as all heck.  I'm wanting to rip through the v1 upgrades as fast as possible so I can catch the world up to what you two are up to.

**Comment by daniel-lewis-ab** [comment]
Interesting.  We does the web directory branch do, curious what the pattern
is - if its already on chat, ignore this and I'll see it when I get home.

**Comment by liusida** [comment]
> Unique thing I've noticed couple custom_nodes use "web" const directory to do stuff.
The custom nodes do all kinds of unexpected things... xD
